from typing import Any, List, Dict

RAW_INFO: Dict[str, List[Dict[str, Any]]] = {
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1001/48000",
            "codec_tag_string": "avc1",
            "codec_tag": "0x31637661",
            "width": 1920,
            "height": 800,
            "coded_width": 1920,
            "coded_height": 800,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "12:5",
            "pix_fmt": "yuv420p",
            "level": 41,
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "24000/1001",
            "time_base": "1/24000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 168240072,
            "duration": "7010.003000",
            "bit_rate": "2150207",
            "bits_per_raw_sample": "8",
            "nb_frames": "168072",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
            },
            "tags": {"language": "und", "handler_name": "VideoHandler"},
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "mp4a",
            "codec_tag": "0x6134706d",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/48000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 336480768,
            "duration": "7010.016000",
            "bit_rate": "143882",
            "max_bit_rate": "143882",
            "nb_frames": "328597",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
            },
            "tags": {"language": "und", "handler_name": "SoundHandler"},
        },
    ]
}


TORRENTS: List[Dict[str, Any]] = [
    {
        "added_on": 1612534456,
        "amount_left": 0,
        "auto_tmm": False,
        "availability": -1,
        "category": "1",
        "completed": 1227921990,
        "completion_on": 1612542927,
        "content_path": "/home/user/Downloads/2021-01-11-raspios-buster-armhf.zip",
        "dl_limit": -1,
        "dlspeed": 0,
        "downloaded": 1243692499,
        "downloaded_session": 0,
        "eta": 8640000,
        "f_l_piece_prio": False,
        "force_start": False,
        "hash": "9005f3068fff382eca98cdd6380f08599319520f",
        "last_activity": 0,
        "magnet_uri": "magnet:?xt=urn:btih:9005f3068fff382eca98cdd6380f08599319520f&dn=2021-01-11-raspios-buster-armhf.zip&tr=http%3a%2f%2ftracker.raspberrypi.org%3a6969%2fannounce",
        "max_ratio": -1,
        "max_seeding_time": -1,
        "name": "2021-01-11-raspios-buster-armhf.zip",
        "num_complete": 0,
        "num_incomplete": 615,
        "num_leechs": 0,
        "num_seeds": 0,
        "priority": 0,
        "progress": 1,
        "ratio": 6.351007187348165e-05,
        "ratio_limit": -2,
        "save_path": "/home/user/Downloads/",
        "seeding_time_limit": -2,
        "seen_complete": -3600,
        "seq_dl": False,
        "size": 1227921990,
        "state": "pausedUP",
        "super_seeding": False,
        "tags": "",
        "time_active": 14334,
        "total_size": 1227921990,
        "tracker": "",
        "trackers_count": 1,
        "up_limit": -1,
        "uploaded": 78987,
        "uploaded_session": 0,
        "upspeed": 0,
    },
    {
        "added_on": 1612746101,
        "amount_left": 1741422592,
        "auto_tmm": False,
        "availability": 0,
        "category": "2",
        "completed": 0,
        "completion_on": -3600,
        "content_path": "/home/user/Downloads/xubuntu-20.04.2-desktop-amd64.iso",
        "dl_limit": -1,
        "dlspeed": 0,
        "downloaded": 0,
        "downloaded_session": 0,
        "eta": 8640000,
        "f_l_piece_prio": False,
        "force_start": False,
        "hash": "5d6bf814125b1660f29a6841dbb5f6e277eb02cc",
        "last_activity": 1612746105,
        "magnet_uri": "magnet:?xt=urn:btih:5d6bf814125b1660f29a6841dbb5f6e277eb02cc&dn=xubuntu-20.04.2-desktop-amd64.iso&tr=https%3a%2f%2ftorrent.ubuntu.com%2fannounce",
        "max_ratio": -1,
        "max_seeding_time": -1,
        "name": "xubuntu-20.04.2-desktop-amd64.iso",
        "num_complete": 0,
        "num_incomplete": 0,
        "num_leechs": 0,
        "num_seeds": 0,
        "priority": 4,
        "progress": 0,
        "ratio": 0,
        "ratio_limit": -2,
        "save_path": "/home/user/Downloads/",
        "seeding_time_limit": -2,
        "seen_complete": -3600,
        "seq_dl": False,
        "size": 1741422592,
        "state": "stalledDL",
        "super_seeding": False,
        "tags": "",
        "time_active": 0,
        "total_size": 1741422592,
        "tracker": "",
        "trackers_count": 1,
        "up_limit": -1,
        "uploaded": 0,
        "uploaded_session": 0,
        "upspeed": 0,
    },
]


MOVIEDB: Dict[str, Any] = {
    "movie_results": [
        {
            "genre_ids": [18],
            "original_language": "en",
            "original_title": "12 Angry Men",
            "poster_path": "/wh0f80G6GZvYBNiYmvqFngt3IYq.jpg",
            "video": False,
            "vote_average": 8.5,
            "overview": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
            "release_date": "1957-04-10",
            "vote_count": 5322,
            "title": "12 Angry Men",
            "adult": False,
            "backdrop_path": "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
            "id": 389,
            "popularity": 20.461,
        }
    ],
    "person_results": [],
    "tv_results": [],
    "tv_episode_results": [],
    "tv_season_results": [],
}
