# Generated by Django 3.1.5 on 2021-03-17 22:13
from typing import Dict, List

from django.db import migrations

from stream.models import MovieDBCategory

categories: Dict[int, str] = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Science Fiction",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western",
}


def _create_bulk_moviedb_categories(
    MovieDBCategory: MovieDBCategory,
) -> List[MovieDBCategory]:
    return [
        MovieDBCategory(moviedb_id=_id, name=_name) for _id, _name in categories.items()
    ]


def populate_categories(apps, schema_editor):
    MovieDBCategory = apps.get_model("stream", "MovieDBCategory")
    bulk_list: List[MovieDBCategory] = _create_bulk_moviedb_categories(MovieDBCategory)

    MovieDBCategory.objects.bulk_create(bulk_list)


def erase_categories(apps, schema_editor):
    MovieDBCategory = apps.get_model("stream", "MovieDBCategory")
    bulk_list: List[int] = list(categories.keys())

    MovieDBCategory.objects.filter(moviedb_id__in=bulk_list).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0001_init_models"),
    ]

    operations = [migrations.RunPython(populate_categories, erase_categories)]
