# Generated by Django 3.1.5 on 2021-03-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0003_change_my_list_movie_to_foreign_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermoviehistory",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="stream.movie",
            ),
        ),
    ]
