# Generated by Django 3.1.7 on 2021-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0004_alter_user_movie_history_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesubtitle",
            name="lang_three",
            field=models.CharField(default="eng", max_length=3),
        ),
    ]
