function languageCodes() {
  return [
    { iso: 'abk', name: 'Abkhazian' },
    { iso: 'aar', name: 'Afar' },
    { iso: 'afr', name: 'Afrikaans' },
    { iso: 'aka', name: 'Akan' },
    { iso: 'alb', name: 'Albanian' },
    { iso: 'amh', name: 'Amharic' },
    { iso: 'ara', name: 'Arabic' },
    { iso: 'arg', name: 'Aragonese' },
    { iso: 'arm', name: 'Armenian' },
    { iso: 'asm', name: 'Assamese' },
    { iso: 'ava', name: 'Avaric' },
    { iso: 'ave', name: 'Avestan' },
    { iso: 'aym', name: 'Aymara' },
    { iso: 'aze', name: 'Azerbaijani' },
    { iso: 'bam', name: 'Bambara' },
    { iso: 'bak', name: 'Bashkir' },
    { iso: 'baq', name: 'Basque' },
    { iso: 'bel', name: 'Belarusian' },
    { iso: 'ben', name: 'Bengali' },
    { iso: 'bih', name: 'Bihari languages' },
    { iso: 'bis', name: 'Bislama' },
    { iso: 'nob', name: 'Bokmål, Norwegian; Norwegian Bokmål' },
    { iso: 'bos', name: 'Bosnian' },
    { iso: 'bre', name: 'Breton' },
    { iso: 'bul', name: 'Bulgarian' },
    { iso: 'bur', name: 'Burmese' },
    { iso: 'cat', name: 'Catalan; Valencian' },
    { iso: 'khm', name: 'Central Khmer' },
    { iso: 'cha', name: 'Chamorro' },
    { iso: 'che', name: 'Chechen' },
    { iso: 'nya', name: 'Chichewa; Chewa; Nyanja' },
    { iso: 'chi', name: 'Chinese' },
    { iso: 'chu', name: 'Church Slavic; Slavonic; Old Bulgarian' },
    { iso: 'chv', name: 'Chuvash' },
    { iso: 'cor', name: 'Cornish' },
    { iso: 'cos', name: 'Corsican' },
    { iso: 'cre', name: 'Cree' },
    { iso: 'hrv', name: 'Croatian' },
    { iso: 'cze', name: 'Czech' },
    { iso: 'dan', name: 'Danish' },
    { iso: 'div', name: 'Divehi; Dhivehi; Maldivian' },
    { iso: 'dut', name: 'Dutch; Flemish' },
    { iso: 'dzo', name: 'Dzongkha' },
    { iso: 'eng', name: 'English' },
    { iso: 'epo', name: 'Esperanto' },
    { iso: 'est', name: 'Estonian' },
    { iso: 'ewe', name: 'Ewe' },
    { iso: 'fao', name: 'Faroese' },
    { iso: 'fij', name: 'Fijian' },
    { iso: 'fin', name: 'Finnish' },
    { iso: 'fre', name: 'French' },
    { iso: 'ful', name: 'Fulah' },
    { iso: 'gla', name: 'Gaelic; Scottish Gaelic' },
    { iso: 'glg', name: 'Galician' },
    { iso: 'lug', name: 'Ganda' },
    { iso: 'geo', name: 'Georgian' },
    { iso: 'ger', name: 'German' },
    { iso: 'gre', name: 'Greek, Modern (1453-)' },
    { iso: 'grn', name: 'Guarani' },
    { iso: 'guj', name: 'Gujarati' },
    { iso: 'hat', name: 'Haitian; Haitian Creole' },
    { iso: 'hau', name: 'Hausa' },
    { iso: 'heb', name: 'Hebrew' },
    { iso: 'her', name: 'Herero' },
    { iso: 'hin', name: 'Hindi' },
    { iso: 'hmo', name: 'Hiri Motu' },
    { iso: 'hun', name: 'Hungarian' },
    { iso: 'ice', name: 'Icelandic' },
    { iso: 'ido', name: 'Ido' },
    { iso: 'ibo', name: 'Igbo' },
    { iso: 'ind', name: 'Indonesian' },
    { iso: 'ina', name: 'Interlingua' },
    { iso: 'ile', name: 'Interlingue; Occidental' },
    { iso: 'iku', name: 'Inuktitut' },
    { iso: 'ipk', name: 'Inupiaq' },
    { iso: 'gle', name: 'Irish' },
    { iso: 'ita', name: 'Italian' },
    { iso: 'jpn', name: 'Japanese' },
    { iso: 'jav', name: 'Javanese' },
    { iso: 'kal', name: 'Kalaallisut; Greenlandic' },
    { iso: 'kan', name: 'Kannada' },
    { iso: 'kau', name: 'Kanuri' },
    { iso: 'kas', name: 'Kashmiri' },
    { iso: 'kaz', name: 'Kazakh' },
    { iso: 'kik', name: 'Kikuyu; Gikuyu' },
    { iso: 'kin', name: 'Kinyarwanda' },
    { iso: 'kir', name: 'Kirghiz; Kyrgyz' },
    { iso: 'kom', name: 'Komi' },
    { iso: 'kon', name: 'Kongo' },
    { iso: 'kor', name: 'Korean' },
    { iso: 'kua', name: 'Kuanyama; Kwanyama' },
    { iso: 'kur', name: 'Kurdish' },
    { iso: 'lao', name: 'Lao' },
    { iso: 'lat', name: 'Latin' },
    { iso: 'lav', name: 'Latvian' },
    { iso: 'lim', name: 'Limburgan; Limburger; Limburgish' },
    { iso: 'lin', name: 'Lingala' },
    { iso: 'lit', name: 'Lithuanian' },
    { iso: 'lub', name: 'Luba-Katanga' },
    { iso: 'ltz', name: 'Luxembourgish; Letzeburgesch' },
    { iso: 'mac', name: 'Macedonian' },
    { iso: 'mlg', name: 'Malagasy' },
    { iso: 'may', name: 'Malay' },
    { iso: 'mal', name: 'Malayalam' },
    { iso: 'mlt', name: 'Maltese' },
    { iso: 'glv', name: 'Manx' },
    { iso: 'mao', name: 'Maori' },
    { iso: 'mar', name: 'Marathi' },
    { iso: 'mah', name: 'Marshallese' },
    { iso: 'mon', name: 'Mongolian' },
    { iso: 'nau', name: 'Nauru' },
    { iso: 'nav', name: 'Navajo; Navaho' },
    { iso: 'nde', name: 'Ndebele, North; North Ndebele' },
    { iso: 'nbl', name: 'Ndebele, South; South Ndebele' },
    { iso: 'ndo', name: 'Ndonga' },
    { iso: 'nep', name: 'Nepali' },
    { iso: 'sme', name: 'Northern Sami' },
    { iso: 'nor', name: 'Norwegian' },
    { iso: 'nno', name: 'Norwegian Nynorsk; Nynorsk, Norwegian' },
    { iso: 'oci', name: 'Occitan (post 1500)' },
    { iso: 'oji', name: 'Ojibwa' },
    { iso: 'ori', name: 'Oriya' },
    { iso: 'orm', name: 'Oromo' },
    { iso: 'oss', name: 'Ossetian; Ossetic' },
    { iso: 'pli', name: 'Pali' },
    { iso: 'pan', name: 'Panjabi; Punjabi' },
    { iso: 'per', name: 'Persian' },
    { iso: 'pol', name: 'Polish' },
    { iso: 'por', name: 'Portuguese' },
    { iso: 'pus', name: 'Pushto; Pashto' },
    { iso: 'que', name: 'Quechua' },
    { iso: 'rum', name: 'Romanian; Moldavian; Moldovan' },
    { iso: 'roh', name: 'Romansh' },
    { iso: 'run', name: 'Rundi' },
    { iso: 'rus', name: 'Russian' },
    { iso: 'smo', name: 'Samoan' },
    { iso: 'sag', name: 'Sango' },
    { iso: 'san', name: 'Sanskrit' },
    { iso: 'srd', name: 'Sardinian' },
    { iso: 'srp', name: 'Serbian' },
    { iso: 'sna', name: 'Shona' },
    { iso: 'iii', name: 'Sichuan Yi; Nuosu' },
    { iso: 'snd', name: 'Sindhi' },
    { iso: 'sin', name: 'Sinhala; Sinhalese' },
    { iso: 'slo', name: 'Slovak' },
    { iso: 'slv', name: 'Slovenian' },
    { iso: 'som', name: 'Somali' },
    { iso: 'sot', name: 'Sotho, Southern' },
    { iso: 'spa', name: 'Spanish; Castilian' },
    { iso: 'sun', name: 'Sundanese' },
    { iso: 'swa', name: 'Swahili' },
    { iso: 'ssw', name: 'Swati' },
    { iso: 'swe', name: 'Swedish' },
    { iso: 'tgl', name: 'Tagalog' },
    { iso: 'tah', name: 'Tahitian' },
    { iso: 'tgk', name: 'Tajik' },
    { iso: 'tam', name: 'Tamil' },
    { iso: 'tat', name: 'Tatar' },
    { iso: 'tel', name: 'Telugu' },
    { iso: 'tha', name: 'Thai' },
    { iso: 'tib', name: 'Tibetan' },
    { iso: 'tir', name: 'Tigrinya' },
    { iso: 'ton', name: 'Tonga (Tonga Islands)' },
    { iso: 'tso', name: 'Tsonga' },
    { iso: 'tsn', name: 'Tswana' },
    { iso: 'tur', name: 'Turkish' },
    { iso: 'tuk', name: 'Turkmen' },
    { iso: 'twi', name: 'Twi' },
    { iso: 'uig', name: 'Uighur; Uyghur' },
    { iso: 'ukr', name: 'Ukrainian' },
    { iso: 'urd', name: 'Urdu' },
    { iso: 'uzb', name: 'Uzbek' },
    { iso: 'ven', name: 'Venda' },
    { iso: 'vie', name: 'Vietnamese' },
    { iso: 'vol', name: 'Volapük' },
    { iso: 'wln', name: 'Walloon' },
    { iso: 'wel', name: 'Welsh' },
    { iso: 'fry', name: 'Western Frisian' },
    { iso: 'wol', name: 'Wolof' },
    { iso: 'xho', name: 'Xhosa' },
    { iso: 'yid', name: 'Yiddish' },
    { iso: 'yor', name: 'Yoruba' },
    { iso: 'zha', name: 'Zhuang; Chuang' },
    { iso: 'zul', name: 'Zulu' },
  ];
}

export default languageCodes;
