# Generated by Django 3.1.5 on 2021-03-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stream", "0001_init_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="MudSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("source", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MovieTorrent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "movie_content",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stream.moviecontent",
                    ),
                ),
            ],
        ),
    ]
