# Generated by Django 3.1.7 on 2021-03-29 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_init_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="movietorrent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
